apiVersion: v1
kind: Namespace
metadata:
  name: demo-namespace
---
apiVersion: v1
kind: Service
metadata:
  namespace: demo-namespace
  name: demo-service
spec:
  type: NodePort
  selector:
    app: demo-deployment
  ports:
    - port: 80
      targetPort: 8080
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 30007
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: demo-namespace
  name: demo-deployment
  labels:
    app: demo-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-deployment
  template:
    metadata:
      labels:
        app: demo-deployment
    spec:
      containers:
      - name: demo-kubernetes-application
        image: demo-app:1
        resources:
          requests:
            memory: 64Mi
            cpu: 250m
          limits:
            memory: 128Mi
            cpu: 500m
        ports:
          - containerPort: 8080
